### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by wen-gg** [rocky-git/ex-admin-webman#1]
1.建议不要强制覆盖.env文件，如果需要追加数据都可以
2.不知怎么回事，我本地安装后登录显示成功，但是不跳转
![微信图片_20221108161253](https://user-images.githubusercontent.com/17865026/200510161-5a3c32d3-50d3-4989-834c-734239baed77.jpg)

3.这个 https://github.com/rocky-git/ex-admin-ui/blob/master/src/Route.php 文件170行应该有点问题
4.如果可以，支持下illuminate 9.0版本

**Comment by rocky-git** [comment]
要求php版本7.4,redis能否写入缓存排查

关于强制覆盖.env文件，已调整
illuminate 9.0版本需要php8，暂不适配php8

**Comment by wen-gg** [comment]
token生成失败了
![截图 2022-11-08 17-23-30](https://user-images.githubusercontent.com/17865026/200526438-270bb03c-a8df-47f7-a899-9e9fe762fb16.png)

**Comment by rocky-git** [comment]
刚刚也有用户发现，发现有些不支持这个加密方式，已调整
<img width="758" alt="image" src="https://user-images.githubusercontent.com/44958386/200526832-61d391d8-6f8a-436b-bc58-527db330c69d.png">

**Comment by wen-gg** [comment]
感谢，可以了
