### ISSUE TITLE
league/flysystem能用2.5.0吗？我的其他插件用的是250

### ISSUE THREAD

**Issue by pengdefang** [rocky-git/ex-admin-webman#4]

**Comment by rocky-git** [comment]
需要自己动手下哦，addons/webman/filesystem目录里的适配器

**Comment by pengdefang** [comment]
> 需要自己动手下哦，addons/webman/filesystem目录里的适配器
但是会报错呀！
composer require rockys/ex-admin-webman
Problem 1
    - rockys/ex-admin-webman[1.0.0, ..., 1.0.1] require league/flysystem ^1 -> found league/flysystem[1.0.0, ..., 1.1.10] but the package is fixed to 2.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires rockys/ex-admin-webman ^1.0 -> satisfiable by rockys/ex-admin-webman[1.0.0, 1.0.1].

**Comment by rocky-git** [comment]
使用官方源，现在可以尝试安装
