### ISSUE TITLE
表单联动或表单watch功能问题

### ISSUE THREAD

**Issue by pengdefang** [rocky-git/ex-admin-webman#7]
一个地区下拉选项，用的级联选择，选择市后，需要根据选择的市，把这个市下面所有选项都放在另一个select里面供选择，换一个市，select里面的内容就根据城市来数据库中匹配拉取。但是联动或watch都不支持这样。

**Comment by rocky-git** [comment]
级联选择还没支持，暂时可以用select 联动
<img width="835" alt="image" src="https://user-images.githubusercontent.com/44958386/205437274-fffbfcee-7705-4da0-851a-3a291aaad2c3.png">

**Comment by rocky-git** [comment]
load 第二个参数是闭包可能会看的也不清楚，也可用url路径代替闭包

**Comment by pengdefang** [comment]
好的，明白了，谢谢！
