### ISSUE TITLE
升级1.0.2 问题

### ISSUE THREAD

**Issue by aiysya** [rocky-git/ex-admin-webman#8]
"msg": "Illuminate\\Filesystem\\FilesystemAdapter::__construct(): Argument #1 ($driver) must be of type League\\Flysystem\\FilesystemOperator, League\\Flysystem\\Filesystem given, called in D:\\code\\php\\irm\\addons\\webman\\filesystem\\Filesystem.php on line 27",

**Comment by rocky-git** [comment]
1.0.2只是兼容php8，兼容Flysystem 包可用2 ，正常可不升，php7.4正常使用1.0.1就可以
