### ISSUE TITLE
下拉多选项，默认会有一个空白的，提交时会有一个null

### ISSUE THREAD

**Issue by pengdefang** [rocky-git/ex-admin-webman#9]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/117135029/205438533-e5d34842-350f-43a6-8f24-db420a6578d2.png">

**Comment by rocky-git** [comment]
数据正常显示应该是数组，而不是字符串噢，有问题可以进群交流群号:579150457

**Comment by pengdefang** [comment]
> 

$form->select('category_type', '分类')->mode('multiple')->options(Category::selects());
是表格，添加记录时，下拉选项如果是设置的可多选，初始化就会有一个空白的在那，提交时的值是 category_type:[null,2,5]

**Comment by rocky-git** [comment]
->mode('multiple') 改成->multiple()

**Comment by pengdefang** [comment]
> 
好的，谢谢，我可能看文档示例代码时，看到了mode的用法，
